convert_ints_to_floats on old versions of NumPy
Change to using a positional argument which works on old and current versions of NumPy.

The current code using a keyword argument can fail on older versions of NumPy:

```
$ python2.6 -c "import numpy as np; print(np.__version__); print(np.array([1,2,3]).astype(dtype=np.float64))"
1.6.2
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: astype() takes no keyword arguments
```